###
DELETE http://localhost:9000/api/ordenes/dlt=order/5 HTTP/1.1

###
PUT http://localhost:9000/api/empleados/update/userWPttAdm/5 HTTP/1.1
Content-Type: application/json

{
  "typeEmpl": 1,
  "firstName": "Andresito",
  "lastName": "Moncayo Zambrano",
  "numberEmpl": "0989732160",
  "dateNacm": "2021-09-10",
  "emailEmpl": "andres@moncayo.com",
  "newpassword": "andres02"
}

###
POST http://localhost:9000/api/promociones/add-promo HTTP/1.1
Content-Type: application/json

{
    "prod_menu": 1,
    "code": "HOLAMUNDO111",
    "dateIn": "2021-09-05",
    "dateOut": "2021-09-08",
    "desc": 15,
    "descripcion": "Promocíon lista",
    "image_prom": null
}


###
POST http://localhost:9000/api/promociones/insertar/promoproduct HTTP/1.1
Content-Type: application/json

{
    "select":"1",
    "select1":"19"
    
}

###
GET http://localhost:9000/api/ventas/fecha HTTP/1.1

###
PUT http://localhost:9000/api/menu HTTP/1.1

