###
PUT http://localhost:9000/api/ordenes/view/76 HTTP/1.1
###
GET http://localhost:9000/api/ordenes/getOrders HTTP/1.1
# Content-Type: application/json

# {
#     "id": 18,
#     "total": 7.5 
# }


###
POST http://localhost:9000/api/promociones/insertar/promoproduct HTTP/1.1
Content-Type: application/json

{
    "select":"1",
    "select1":"19"
    
}

###
DELETE http://localhost:9000/api/empleados/eliminaremp/5 HTTP/1.1

###
PUT http://localhost:9000/api/empleados/actualizar/empleado-admin/3 HTTP/1.1
Content-Type: application/json

{
    "name": "Leonel",
    "namel": "Anchundia",
    "dat": "2000-08-16",
    "tel": "0987654321",
    "email": "leo@gmail.com",
    "select": "2",
    "id":"3"
    
}